### PR TITLE
[SCSB-145] require Python 3.10

### PR DESCRIPTION
**Pull request by zacharyburnett**
resolves [SCSB-145](https://jira.stsci.edu/browse/SCSB-145)

propagate Astropy's deprecation of Python 3.9 to downstream packages

> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:

### CODE REVIEW

**Comment by BradleySappington** [comment]
Thanks @zacharyburnett, I think that tox.ini and ci_workflows should be updated as well with this PR?  The latter is causing errors trying to install '3.1' which is peculiar...

**Comment by BradleySappington** [comment]
@zacharyburnett - looks like tox still has references to 3.9 and can be moved from 3.10 - 3.12 in the environment setups.
Also pyproject.toml will probably need numpy >=1.21.6

**Comment by mperrin** [comment]
@BradleySappington @zacharyburnett - I wanted to check in for a status on this PR? It would be nice to get this merged in soon if possible, since the py3.9 lack of support is causing test failures for other PRs at this point. Thanks!

**Comment by zacharyburnett** [comment]
> @BradleySappington @zacharyburnett - I wanted to check in for a status on this PR? It would be nice to get this merged in soon if possible, since the py3.9 lack of support is causing test failures for other PRs at this point. Thanks!

I apologize! I have been occupied by the JWST pipeline release and regression tests; these commits look good to me!

**Review by BradleySappington — APPROVED** [review]

**Comment by mperrin** [comment]
Thank you both! 

And no worries, no need to apologize @zacharyburnett. I completely sympathize on having too many things to be occupied with, ha. All too often...

**Pull request merged**
