### PR TITLE
fix syntax error in `.github/workflows/download_data.yml`

### PR DESCRIPTION
**Pull request by zacharyburnett**
sorry about that!

### CODE REVIEW

**Comment by zacharyburnett** [comment]
tested this fix on my fork here: https://github.com/zacharyburnett/webbpsf/actions/runs/9961331877

it successfully downloaded the data and made a cache:
[image](https://github.com/zacharyburnett/webbpsf/actions/caches)

**Comment by zacharyburnett** [comment]
Once this PR is merged you should be able to run the workflow manually to make the first cache, and then all CI will work

**Review by mperrin — APPROVED** [review]

**Comment by mperrin** [comment]
Merged and trying the re-run of the workflow now

**Comment by mperrin** [comment]
looks like it worked, I think?

**Comment by zacharyburnett** [comment]
> looks like it worked, I think?

yeah it looks like it! 
```
Cache restored from key: webbpsf-data-mini-1.3.0
```
https://github.com/spacetelescope/webbpsf/actions/runs/9961521680/job/27523218073#step:5:19

**Pull request merged**
