### PR TITLE
Documentation additions for 1.3

### PR DESCRIPTION
**Pull request by mperrin**
Placeholder PR for improvements and additions to the readthedocs for 1.3. 

1. add show_wfs_around_obs and show_wfs_during_program to the online docs
2. [more tbd?]

Plus some minor incidentals:
 - also some minor tweaks to show_wfs_during_program to improve output plot formatting (in particular, apply clip_on to text dates, so if the user sets start or end dates, labels outside that time range are not shown)

### CODE REVIEW

**Comment by marcio-melendez** [comment]
Hi @mperrin I am trying to add a notebook to this PR but it seems that I don't have permission. Can you allow me to add to this PR? Thanks!

**Comment by marcio-melendez** [comment]
I just added a new notebook with a PSF subtraction example. at the end of the notebook there is the usage for the new function `nrc_ta_image_comparison`

**Comment by marcio-melendez** [comment]
I re-added a notebook with a PSF subtraction example and the `nrc_ta_image_comparison`. I think that during the force-pushed my notebook got lost, so that's why added it again. In any case, @mperrin your notebooks look good to me. Can you take a look at the PSF subtraction notebook and see if it make senses, the idea is to show at least one way to do a PSF subtraction with some know tools.

**Comment by marcio-melendez** [comment]
@mperrin you mentioned that you add some text/comments into the PSF subtraction notebook, is this correct? I don't see a new version of the notebook. Maybe you can upload the version that worked for you, I know there were a couple of old lines  not working.

**Comment by mperrin** [comment]
Yes will do, thanks for the reminder to push those.

**Comment by marcio-melendez** [comment]
@mperrin thanks, this looks really good. Do you have any other document that you think you would like to add to this PR? Or should we go ahead and review/merge so we can move forward with the release?

**Comment by mperrin** [comment]
There's a couple bits of editing I still want to do, to address the feedback in spacetelescope/stpsf#39 about that part of the docs being unclear. I'll try to do that right now

**Comment by mperrin** [comment]
@obi-wan76 OK, I've pushed all the doc updates I plan to do at this time

**Review by marcio-melendez — APPROVED** [review]
This looks good, thanks!

**Pull request merged**
