### PR TITLE
Additional fixes to trending.py

### LINKED ISSUE #677: Trending EE plot normalization issue
Reported by @mlibralato: 
> I'm studying the temporal variations of the ePSFs. I took the code in WebbPSF that show how the encircled energy varies over time and I correlated it with by how much my ePSFs seem to vary over time. I do not see any significant change, as I was told should be at this wavelengths. The comment here is that the code that makes this plot here (https://webbpsf.readthedocs.io/en/latest/jwst_measured_opds.html#Wavefront-Trending-throughout-a-given-month) computes the change in the encircled energy as EE_ref - EE_date but this is not a % change, so the shadowed box that highlight the +/-3% variations is not correct. Do  you agree? I believe that to be consistent the plot should show on the y axis something like (EE_ref-EE_date)/EE_ref

### LINKED ISSUE #683: Add new PIDs from Cycle 2 into webbpsf sensing trending functions
Add PID from Cycle 2 in webbpsf trending scripts. 
https://github.com/spacetelescope/webbpsf/blob/develop/webbpsf/trending.py#L99C5-L99C5

### PR DESCRIPTION
**Pull request by Skyhawk172**
There are multiple fixes folded into this PR, all related to our trending plots.

I noticed an issue in `webbpsf.trending.wfe_histogram_plot` when plotting arrows, where the original hardcoded offset does not scale properly when the `ylimits` change (say, when we change the start and end dates). See screenshot:

Screenshot 2023-07-07 at 4 39 29 PM

This PR addresses this issue for any `ylimits,` as demonstrated below. The correction arrows now go from the edge of the two connecting points, without overlapping with the points:

Screenshot 2023-07-07 at 4 41 21 PM

There are also a few additional fixes that I've stumbled upon over the last months.

### CODE REVIEW

**Comment by Skyhawk172** [comment]
Here's an example of what the PID argument allows:
image

**Comment by Skyhawk172** [comment]
Tests are failing because the last commit requires the import of astroquery

```
ImportError while loading conftest '/home/runner/work/webbpsf/webbpsf/webbpsf/conftest.py'.
webbpsf/__init__.py:96: in <module>
    from . import trending
webbpsf/trending.py:10: in <module>
    from astroquery.mast import Observations
E   ModuleNotFoundError: No module named 'astroquery'
ERROR: InvocationError for command /home/runner/work/webbpsf/webbpsf/.tox/py39-legacy-test/bin/pytest (exited with code 4)
```

**Comment by marcio-melendez** [comment]
@Skyhawk172 as you work on this, can you also  include #677 in this PR? We can iterate on what makes more sense in the trending figure.

**Comment by Skyhawk172** [comment]
Already done, along with #683.

**Review by BradleySappington — APPROVED** [review]
The code itself looks fine.  I do see a lot of magic numbers in there without comments explaining why that specific number is chosen.  You can also "duck type" the numbers as implied constants (all caps) and give them meaningful names to make the calculations more legible.  Lots of these numbers happen with the offsets calculations, and `set_ylim`/`get_ylim`.  

These changes aren't necessary, but make reviews easier and the code more legible/maintanable.  I'll approve and leave it up to you if you'd like to change.

**Comment by BradleySappington** [comment]
Looks like #690 should fix these failing tests

**Comment by BradleySappington** [comment]
@Skyhawk172, would you please do another rebase to verify all tests pass?  Need #704

**Comment by Skyhawk172** [comment]
I merged the latest develop branch, including #704, and only the Sphinx doc build is reporting errors now.

**Comment by Skyhawk172** [comment]
This PR was closed but not merged. I reopened it so I could merge the latest develop with #708, which should fix the Sphinx test. Then it'll be good to merge.

**Pull request merged**
