### PR TITLE
Implement distortion for Roman

### PR DESCRIPTION
**Pull request by Skyhawk172**
Implement geometric distortion for Roman using the Roman SIAF.  It appears we can use the same infrastructure already set up for JWST can be used for Roman as well.

### CODE REVIEW

**Comment by Skyhawk172** [comment]
Current implementation will require installing Python package `soc_roman_tools`, which is where the Roman SIAF is stored.

Also will need to remove the hardcoded path to local WFI Zernike file.

**Comment by Skyhawk172** [comment]
I've done a bunch of tests and I think this PR is good to go. Feedback appreciated. 

One thing I am still unsure of is whether the rotation needs to be applied.

Here are some plots to compare the effect(s) of including distortion on the Roman PSF:

image

image

image

**Comment by Skyhawk172** [comment]
Regarding rotation, I believe that there is no need to apply it, like it is done for JWST NIRCam, NIRISS, and FGS. From email thread with GSFC Optical engineer back in 2020, the "Pupil FITS is FPA coordinate and no need of rotation/flip", which suggests we can use the pupil FITS files as they are for the FFT/MFT propagation.

**Comment by Skyhawk172** [comment]
I also think there is no need to apply a rotation, like what is done for JWST NIRCam, NIRISS, or FGS. (Re-)Reading an email thread with a GSFC optical engineer from 2020, it's mentioned that "Pupil FITS is FPA coordinate and no need of rotation/flip", which suggests the pupil FITS files are already aligned with the detector frame.

Moreover, it also appears the Zernikes as defined in the reference data (see "Zernike NOLL def" tab in the spreadsheet) are properly aligned with the _exit_ (i.e. flipped) pupil, so I don't think we need to do any additional flip/rotation. Confirmation of this would be appreciated.

**Review by marcio-melendez — COMMENTED** [review]
Would you need to add soc_roman_tools as a dependency?

**Comment by Skyhawk172** [comment]
Yes, I think we'll have to add it to the dependencies.

**Comment by marcio-melendez** [comment]
@BradleySappington is this as simple as adding this into the toml file? (soc_roman_tools dependency)

**Comment by BradleySappington** [comment]
> @BradleySappington is this as simple as adding this into the toml file? (soc_roman_tools dependency)

Yes, add it with any preferred versioning to the dependencies section of pyproject.toml

**Comment by Skyhawk172** [comment]
Okay, I can add it to the PR: `"soc_roman_tools>=0.1.0",`, where v0.1.0 is the current version on pypi.

**Review by marcio-melendez — APPROVED** [review]
This looks good.

**Comment by Skyhawk172** [comment]
Other than the approximate V2/V3 location of the Roman Coronagraph, there is not much information available in the SIAF (that information simply does not exist yet), so I had to enforce no distortion for the Roman CGI.

**Comment by Skyhawk172** [comment]
@obi-wan76 @BradleySappington I think this is one is good to go. If you agree, we can fold it in the next release.

**Pull request merged**
