### PR TITLE
Merge setup.cfg to pyproject.toml for Pep621 compliance

### PR DESCRIPTION
**Pull request by BradleySappington**
Merging as many things as possible into pyproject.toml for pep621 compliance.
Flake8 incompatible with pyproject so staying put.
Can move to .flake8 file if we choose to get rid of setup.py and setup.cfg entirely.

### CODE REVIEW

**Comment by BradleySappington** [comment]
@obi-wan76 and @ojustino - Ready for review and testing.

**Review by melanieclarke — APPROVED** [review]
These changes look good to me.

I am not familiar enough with the differences between pyproject.toml and setup.cfg to comment on specific syntax, but by eye, it looks like everything that was in setup.cfg is now in pyproject.toml.  I also did the following spot checks:

- install from source with `pip install -e`, check that version.py was created appropriately
- run tests locally with `tox -e test`, check that tests pass as expected
- run tests locally with [test] requirements and `pytest webbpsf --cov webbpsf`, check that expected statements are omitted from coverage checks
- build docs locally with [docs] requirements and `make html`, check that they build
- run flake8, check that configuration is still picked up from setup.cfg

These spot checks all looked good.  I did note a couple local test failures due to numpy deprecations (np.float no longer exists), but they are unrelated to these changes.

**Comment by BradleySappington** [comment]
@melanieclarke, thank you for you thoroughness!

**Review by marcio-melendez — APPROVED** [review]
Based on comments from Melanie and my own successful  installation from this branch, I think we are good.

**Pull request merged**
