### PR TITLE
597 - add opdtable as positional param to monthly_trending_plot

### PR DESCRIPTION
**Pull request by kulpster85**

### CODE REVIEW

**Review by marcio-melendez — COMMENTED** [review]
This looks good. Just adding the option for the user to provide the OPD table. However, how do you check that the table provide by the user has the same fields as those created by get_opdtable_for_month? e.g.,i'is_pre_correction'  , 'is_post_correction' etc. which are fields that  the monthly trending plot function and get_corrections are expecting to find. Maybe a check that all the keys in this OPD table are the same as the expectations.

**Comment by kulpster85** [comment]
> 

I can add that logic to the changes - that's a good suggestion for robustness.

**Comment by kulpster85** [comment]
> This looks good. Just adding the option for the user to provide the OPD table. However, how do you check that the table provide by the user has the same fields as those created by get_opdtable_for_month? e.g.,i'is_pre_correction' , 'is_post_correction' etc. which are fields that the monthly trending plot function and get_corrections are expecting to find. Maybe a check that all the keys in this OPD table are the same as the expectations.

I have pushed some commits to address your comments @obi-wan76

**Comment by mperrin** [comment]
@obi-wan76 can you re-review or approve this after the changes by @kulpster85 in response to your prior review?  (Like a month ago... I think this is ready to merge but will defer to you to re-review)

**Comment by mperrin** [comment]
This is an old PR, from November, which it looks like @kulpster85 is still waiting for a review from @obi-wan76 for. Trey is this still a relevant/desired PR? If so, reminder to Marcio. :-)

**Comment by kulpster85** [comment]
This would be an efficiency improvement that TAS could leverage to provide the opdtable as an input rather than download the OPDs from MAST.

**Review by marcio-melendez — APPROVED** [review]
I think at that time I reviewed this new changes but never submitted/approve

**Comment by mperrin** [comment]
@obi-wan76 FYI looks like you approved this back in March but never merged it...

**Pull request merged**
