### PR TITLE
683-added cycle-2 PID(s) 4500-4509

### LINKED ISSUE #683: Add new PIDs from Cycle 2 into webbpsf sensing trending functions
Add PID from Cycle 2 in webbpsf trending scripts. 
https://github.com/spacetelescope/webbpsf/blob/develop/webbpsf/trending.py#L99C5-L99C5

### PR DESCRIPTION
**Pull request by kulpster85**
683-Added cycle-2 PID(s) 4500-4509

Close #683

### CODE REVIEW

**Comment by Skyhawk172** [comment]
Hey @kulpster85, I had already linked and folded this issue #683 into another open PR (#688). I'll leave it up to you guys to decide how to best do it @obi-wan76

**Comment by kulpster85** [comment]
@Skyhawk172 can I just link that issue here and consider it close with this pull-request or is something else needed?

**Review by marcio-melendez — APPROVED** [review]
This looks good. For the next release we may want to find a way to retrieve the PID for the sensing programs automatically without hardcoding them inside.

**Comment by marcio-melendez** [comment]
Once #688 is merged, I can close this PR without merging.

**Comment by kulpster85** [comment]
Oh I didn't realize there was already the other pull request with the changes so I'm going to close my pull request

**Pull request closed without merging**
