### PR TITLE
add trending plot function "show_wfs_around_obs"

### PR DESCRIPTION
**Pull request by mperrin**
Simple PR, adds one function "show_wfs_around_obs" that displays the WFS before and after a given science observation, and the spacing in time between those observations. 

Low priority addition, not critical, but I wrote this function a while ago and wanted to get it into a PR. 

example_output_plot

### CODE REVIEW

**Comment by marcio-melendez** [comment]
Great addition. Again a test with a NIRCam LW. Everything looks good. 
image

**Comment by marcio-melendez** [comment]
Looking at your example, why is the WFE the same before/after if there was a big tilt event in between? The top panel is the WFE, right?

**Comment by mperrin** [comment]
Top panel actually just a horizontal timeline; there is no significance to any vertical axis there. Just separation in time horizontally.  It could be changed to be an RMS, in some future PR, but I made this top panel just showing time on one axis and nothing else.

**Review by marcio-melendez — APPROVED** [review]
looks good.

**Pull request merged**
