### PR TITLE
Update citations

### PR DESCRIPTION
**Pull request by BradleySappington**
Establishing a CITATIONS.cff file to be in line with citation best practices.  If anyone is going to use the software for data, or for a reference in a repository or paper, then the credits for this software will be maintained in the CFF file (which gets pushed into the zenodo doi through our repository).  So this will be used for giving credits for authors (in the exact versioning) for any papers/software where WebbPSF will be used.

### CODE REVIEW

**Comment by BradleySappington** [comment]
I added @Skyhawk172 and @mperrin myself.  Couldn't find other orchids from contributors in our slack channel who are affiliated with Space Telescope Science Institute

**Comment by mperrin** [comment]
Let me ping here some other past contributors to webbpsf, in case any of them would like to also be included in the author list as recorded in the `CITATIONS.cff` file. If any of you excellent folks would like to also be included in that, can you please provide us here with your ORCID ID, etc? 

@shanosborne @joseph-long @robelgeda @JarronL

**Comment by joseph-long** [comment]
Thanks for the heads-up @mperrin ! My current employment details can be found here: https://orcid.org/0000-0003-1905-9443

I think it would be a good idea to preserve the references to cite-able entities like SPIE proceedings (that this pull request removes) somewhere, either in the docs or the README. I have also seen a `.bib` file in the repo root used as a de-facto standard in the machine learning world, which I like because I already use BibTeX. (That could also contain the ASCL reference as a `@misc`.)

**Comment by shanosborne** [comment]
Hey, yeah my id and info is all here: https://orcid.org/0009-0001-8609-1518 - thanks!

**Comment by robelgeda** [comment]
Thank you for pinging us @mperrin ! 
My id is here:

```
  - given-names: Robel
    family-names: Geda
    affiliation: Princeton University
    orcid: 'https://orcid.org/0000-0003-1509-9966'
```

**Comment by BradleySappington** [comment]
@mperrin @obi-wan76 I think we are good to review/merge this is, we can update outliers in future PRs.

**Review by mperrin — APPROVED** [review]
👍

**Pull request merged**
